// <auto-generated />
using System;
using CoronaApp.Dal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaApp.Dal.Migrations;
[DbContext(typeof(CoronaContext))]
partial class CoronaContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "3.1.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("CoronaApp.Dal.Models.Location", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Adress")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("City")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PatientId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("Location");
            });

        modelBuilder.Entity("CoronaApp.Dal.Models.LogMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Message")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ThreadId")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("Timestamp")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("Log");
            });

        modelBuilder.Entity("CoronaApp.Dal.Models.Patient", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("Age")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Patient");
            });

        modelBuilder.Entity("CoronaApp.Dal.Models.Location", b =>
            {
                b.HasOne("CoronaApp.Dal.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId");
            });
#pragma warning restore 612, 618
    }
}
